# Generated by Django 2.2.4 on 2020-01-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('INFO', 'info'), ('SUCCESS', 'success'), ('WARNING', 'warning'), ('ERROR', 'error')], max_length=255, null=True)),
                ('unread', models.BooleanField(default=True, verbose_name='mark')),
                ('actor_type', models.CharField(blank=True, choices=[('SERVICE', 'service'), ('USER', 'user')], max_length=255, null=True)),
                ('actor_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='actor short ID')),
                ('recipient_type', models.CharField(blank=True, choices=[('SERVICE', 'service'), ('USER', 'user')], max_length=255, null=True)),
                ('recipient_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='recipient short ID')),
                ('verb', models.TextField(blank=True, null=True, verbose_name='Action Description')),
                ('nf_type', models.CharField(default='default', max_length=20, verbose_name='Type of notification')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Notification Description')),
                ('target_type', models.CharField(blank=True, choices=[('OBJ', 'object'), ('IMG', 'image'), ('URL', 'url')], max_length=255, null=True)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='target short ID')),
                ('type', models.CharField(blank=True, choices=[('UI', 'ui'), ('EMAIL', 'email'), ('SERVICE', 'service')], max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False, verbose_name='Read status')),
                ('deleted', models.BooleanField(default=False, verbose_name='Soft delete status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
