# Generated by Django 2.2.4 on 2020-01-17 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ui_notif', '0002_remove_notification_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='unread',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='deletd_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_action',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='retry action'),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_log',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='retry action'),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 17, 14, 39, 6, 585437, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='target url'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='nf_type',
            field=models.CharField(blank=True, choices=[('UI', 'ui'), ('EMAIL', 'email'), ('SERVICE', 'service')], max_length=255, null=True),
        ),
    ]
